<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [4]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists


def matrix_mul():            #creating matrix_mul function
   
    m = int(input("no of rows in matrix 1: "))        #Taking input from the user to matrix_1
    n = int(input("no of columns in matrix 1: "))

    mat1 = []                    #creating a list matrix_1

    for i in range(0, m):
        mat1.append([])          #appending the values to matrix_1
    
    print("                        ")
    print("the values of mat1 are : ")  

    for i in range(0, m):
        for j in range(0, n):
            mat1[i].append(j)
            mat1[i][j] = 0
            mat1[i][j] = int(input("the value of row " + str(i+1) + " col " + str(j+1) + "  : "))  
    print(mat1)
    print("                        ")
    print("                        ")        
    print("                        ")       


    p = int(input("no of rows in matrix 2 : "))
    q = int(input("no of columns in matrix 2 : "))

    mat2 = []                # creating a matrix_2

    for i in range(0, p):
        mat2.append([])
    
    print("                        ")
    print("the values of mat2 are : ") 

    for i in range(0, p):
        for j in range(0, q):
            mat2[i].append(j)
            mat2[i][j] = 0
            mat2[i][j] = int(input("the value of row " + str(i+1) + " col " + str(j+1) + "  : "))
    print(mat2)
    
    

    result = []             
    for i in range(0, m):
        result.append([])
    for i in range(0, m):
        for j in range(0, q):
            result[i].append(j)
            result[i][j] = 0
            
    

    for i in range(len(mat1)):
        for j in range(len(mat2[0])):
            for k in range(len(mat2)):
                if(len(mat1) != len(mat2)):
                    print("matrix mul is not possible")    
                    return
                else:
                    result[i][j] += mat1[i][k] * mat2[k][j]   #matrix multiplication fromula 
                
    return(result)  #returning the result 
            
    
            
        


In [2]:
matrix_mul()    #calling the matrix_mul function 

no of rows in matrix 1: 3
no of columns in matrix 1: 3
                        
the values of mat1 are : 
the value of row 1 col 1  : 1
the value of row 1 col 2  : 3
the value of row 1 col 3  : 4
the value of row 2 col 1  : 2
the value of row 2 col 2  : 5
the value of row 2 col 3  : 7
the value of row 3 col 1  : 5
the value of row 3 col 2  : 9
the value of row 3 col 3  : 6
[[1, 3, 4], [2, 5, 7], [5, 9, 6]]
                        
                        
                        
no of rows in matrix 2 : 3
no of columns in matrix 2 : 3
                        
the values of mat2 are : 
the value of row 1 col 1  : 1
the value of row 1 col 2  : 0
the value of row 1 col 3  : 0
the value of row 2 col 1  : 0
the value of row 2 col 2  : 1
the value of row 2 col 3  : 0
the value of row 3 col 1  : 0
the value of row 3 col 2  : 0
the value of row 3 col 3  : 1
[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

In [12]:
matrix_mul()

no of rows in matrix 1: 2
no of columns in matrix 1: 2
                        
the values of mat1 are : 
the value of row 1 col 1  : 1
the value of row 1 col 2  : 2
the value of row 2 col 1  : 3
the value of row 2 col 2  : 4
[[1, 2], [3, 4]]
                        
                        
                        
no of rows in matrix 2 : 2
no of columns in matrix 2 : 5
                        
the values of mat2 are : 
the value of row 1 col 1  : 1
the value of row 1 col 2  : 2
the value of row 1 col 3  : 3
the value of row 1 col 4  : 4
the value of row 1 col 5  : 5
the value of row 2 col 1  : 5
the value of row 2 col 2  : 6
the value of row 2 col 3  : 7
the value of row 2 col 4  : 8
the value of row 2 col 5  : 9
[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]


[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

In [5]:
matrix_mul()

no of rows in matrix 1: 2
no of columns in matrix 1: 2
                        
the values of mat1 are : 
the value of row 1 col 1  : 1
the value of row 1 col 2  : 2
the value of row 2 col 1  : 3
the value of row 2 col 2  : 4
[[1, 2], [3, 4]]
                        
                        
                        
no of rows in matrix 2 : 4
no of columns in matrix 2 : 2
                        
the values of mat2 are : 
the value of row 1 col 1  : 1
the value of row 1 col 2  : 4
the value of row 2 col 1  : 5
the value of row 2 col 2  : 6
the value of row 3 col 1  : 7
the value of row 3 col 2  : 8
the value of row 4 col 1  : 9
the value of row 4 col 2  : 6
[[1, 4], [5, 6], [7, 8], [9, 6]]
matrix mul is not possible


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [44]:
import random    
from random import uniform
#importing the random fun
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


A = [0,5,27,6,13,28,100,45,10,79]

# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    val = 0
    sum1 = sum(A)
    prob = [round(i/sum1,4) for i in A]    #it will cheks the probability of a number in given range
    
    cd = []
    c = 0
    for i in range(len(prob)):
        c += prob[i]
        cd.append(c)            #appending the values to the list "C"
        
        
    for i in range(len(A)):
        rand = uniform(0,1)          #usinf uniform function 
        for j in range(len(A)):
            if rand <= cd[j]:
                return A[j]

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number, end = " ")     #print's the number

sampling_based_on_magnitued()        #calling the function


45 79 100 100 100 27 79 45 100 79 45 27 27 27 79 79 13 28 45 79 45 79 28 100 100 28 79 79 28 100 45 100 79 100 79 100 79 100 79 79 100 79 79 6 79 79 100 100 27 13 100 100 45 5 100 100 27 10 45 100 13 100 28 79 79 28 79 100 79 6 100 100 100 100 100 10 45 79 28 79 79 100 100 79 28 100 28 45 79 100 79 45 100 79 27 100 79 45 100 

<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [4]:
import re   #importing the regular expressions 
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits():
    str = input()
    x = re.sub("\D", "",str)   #"\D" matches any charecter/word which present in the input
    y = re.sub("\d","#",x)     #"\d" matches any decimal/num present in the input
    return(y) # modified string which is after replacing the # with digits

replace_digits()   #calling the fun

234


'###'

In [6]:
replace_digits()

a2b3c4


'###'

In [7]:
replace_digits()

abc


''

In [8]:
replace_digits()

#2a$#b%c%561#


'####'

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [58]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure


def display_dash_board(students, marks):     #creating a Function of Students and marks
    students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
    marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
    list1 = dict(zip(students,marks))        #converting students,marks into dictionary list1
    print("display_dash_board values are : ")
    print("          ")
    for key,values in list1.items():
        print(key,":", values)      #printing key and values in a dictionary in list1
    
    print("          ")
    print("          ")

    # write code for computing top top 5 students
    print("Top 5 Students are :")   
    print("          ")
    for key, value in sorted(list1.items(), key=lambda item: item[1],reverse = True)[0:5]:  #sorting the dictionary top 5 values 
        top_5_students = ("%s: %s" % (key, value))   #stroing values into a list
        print( top_5_students)    #prints top 5 students 
    
    print("         ")
    print("         ")
    
    # write code for computing top least 5 students
    print("The least 5 Students are :")
    print("          ")
    for key, value in sorted(list1.items(), key=lambda item: item[1])[0:5]:
        least_5_students = ("%s: %s" % (key, value))
        print(least_5_students)
    
    print("        ")
    print("        ")

    # write code for computing top least 5 students
    print("students_within_25_and_75 percentile are :")
    print("          ")
    for key, value in sorted(list1.items(), key=lambda item: item[1]):
        n = len(marks)
        per25 = int(n/4) if (n/4).is_integer() else int(n/4)     #caliculating the 25% of values
        per75 = int(3*n/4)                                       #caliculating the 75% of values
        num = sorted(list1.items(), key=lambda item:item[1]) [per25:per75]   #store the values between 25% and 75%
        return num              #return the values

   


display_dash_board(students, marks)      #calling the function



display_dash_board values are : 
          
student1 : 45
student2 : 78
student3 : 12
student4 : 14
student5 : 48
student6 : 43
student7 : 47
student8 : 98
student9 : 35
student10 : 80
          
          
Top 5 Students are :
          
student8: 98
student10: 80
student2: 78
student5: 48
student7: 47
         
         
The least 5 Students are :
          
student3: 12
student4: 14
student9: 35
student6: 43
student1: 45
        
        
students_within_25_and_75 percentile are :
          


[('student9', 35),
 ('student6', 43),
 ('student1', 45),
 ('student7', 47),
 ('student5', 48)]


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [21]:
import math        #importing math library

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
#list = []
def closest_points_to_p():
    list = []
    for i in S:
        for j in P:
            a = ((i[0] * j[0]) + (i[1] * j[1]))
            b = math.sqrt(i[0]**2 + i[1]**2)
            c = math.sqrt(j[0]**2 + j[1]**2)
            value = math.acos(a/(b*c))           #using cos inverse function 
            list.append(value)                   #appending/adding the values into list
    cos_dis = dict(zip(S,list))
    sorted_cos_dist = sorted(cos_dis.items(), key = lambda xy: (xy[1], xy[0]))[0:5]
    for i in range(5):
        print(sorted_cos_dist[i][0])



S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= [(3,-4)]
points = closest_points_to_p()


(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [63]:
import math
import re 
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):    #creating a fun
    result = "NO"     
    
    a = float(re.split("x",line)[0])
    b = float(re.split("x",(re.split("y",line)[0]))[1])
    c = float(re.split("y",line)[-1])     #extracting  the values a,b,c from the given lines and stores the values
    
              
              
    red1 = []
    blue1 = []
    for x,y in red:                    #it will checks all the RED points at on side of line or not
        red1.append(a* +b*y >= c)
    for x,y in blue:
        blue1.append(a*x + b*y >= c)   #it will checks all the BLUE points are at on side of a line or not
              
    if all(red1) and not all (blue1):
              result = "YES"
    
    return result                       #returning the result

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) 

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [16]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
import re             #importing regular expressions 
def curve_smoothing(S):
    S = input("input :")     #takes input from the user
    pattern = '\d+'
    ls_num=re.findall(pattern, S)   # list of numeral present in string
    pattern = '\d+'
    spaces = re.split(pattern, S)  # split string to seperate '_' spaces

    if len(spaces[0])==0 and len(ls_num)==1:
        Space_num=len(re.findall('_',  S))
        sums=int(ls_num[0])
        repl_int=round(sums/(Space_num+1))
        S=re.sub(r'(\d{2})(,_)', r'{}\2'.format(str(repl_int)) , S, 1)
        S=re.sub('_', str(repl_int),S, Space_num)
        return S

    elif len(spaces[0])==0 and len(ls_num)>1:
        for i in range(1,len(spaces)):
            if i==1:
                Space_num=len(re.findall('_',  spaces[i]))
                sums=int(ls_num[i-1])+int(ls_num[(i)])
                repl_int=round(sums/(Space_num+2))
                S=re.sub(str(ls_num[i-1]), str(repl_int),S)
                S=re.sub('_', str(repl_int),S, Space_num)
                S=re.sub(str(ls_num[i]), str(repl_int),S,1)
                ls_num[i]=repl_int
            elif i<len(ls_num):
                Space_num=len(re.findall('_',  spaces[i]))
                sums=int(ls_num[i-1])+int(ls_num[(i)])
                repl_int=round(sums/(Space_num+2))
                S=re.sub(r'(\d{2})(,_)', r'{}\2'.format(str(repl_int)) , S, 1)
                S=re.sub('_', str(repl_int),S, Space_num)
                S=re.sub(str(ls_num[i]), str(repl_int),S,1)
                ls_num[i]=repl_int
            elif len(spaces[-1])!=0:
                Space_num=len(re.findall('_',  spaces[i]))
                repl_int=round(ls_num[(i-1)]/(Space_num+1))
                S=re.sub(r'(\d{2})(,_)', r'{}\2'.format(str(repl_int)) , S, 1)
                S=re.sub('_', str(repl_int),S, Space_num)
        return S


    else:
        for i in range(len(spaces)):
            if i==0:
                Space_num=len(re.findall('_',  spaces[i]))
                sums=int(ls_num[(i)])
                repl_int=round(sums/(Space_num+1))
                S=re.sub(r'(\d{2})(,_)', r'{}\2'.format(str(repl_int)) , S, 1)
                S=re.sub('_', str(repl_int),S, Space_num)
                S=re.sub(str(ls_num[i]), str(repl_int),S, 1)
                ls_num[i]=repl_int
            elif i>=1 and i<len(ls_num):
                Space_num=len(re.findall('_',  spaces[i]))
                sums=int(ls_num[i-1])+int(ls_num[(i)])
                repl_int=round(sums/(Space_num+2))
                S=re.sub(r'(\d{2})(,_)', r'{}\2'.format(str(repl_int)) , S, 1)
                S=re.sub('_', str(repl_int),S, Space_num)
                S=re.sub(str(ls_num[i]), str(repl_int),S,1)
                ls_num[i]=repl_int
            elif len(spaces[-1])!=0:
                Space_num=len(re.findall('_',  spaces[i]))
                repl_int=round(ls_num[(i-1)]/(Space_num+1))
                S=re.sub(r'(\d{2})(,_)', r'{}\2'.format(str(repl_int)) , S, 1)
                S=re.sub('_', str(repl_int),S, Space_num)
        return S        #returning the values 


curve_smoothing(string)  #calling the function

input :_,_,_,24


'6,6,6,6'

In [17]:
curve_smoothing(string)

input :40,_,_,_,60


'20,20,20,20,20'

In [18]:
curve_smoothing(string)

input :80,_,_,_,_


'16,16,16,16,16'

In [19]:
curve_smoothing(string)

input :_,_,30,_,_,_,50,_,_


'10,10,12,12,12,12,4,4,4'

<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [36]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

def compute_conditional_probabilites(F,S):
    num=0
    den=0
    for i in range(len(A)):
        if(A[i][1] == S):
            den += 1
            if(A[i][0] == F):
                num +=1
    print('P(F={}|S=={}) ='.format(F,S), Fraction(num,den))

for k in ['F1', 'F2', 'F3', 'F4', 'F5']:    #the values are present in list F
    for m in ['S1', 'S2', 'S3']:            #the values are present in list S
        compute_conditional_probabilites(k,m)

P(F=F1|S==S1) = 1/4
P(F=F1|S==S2) = 1/3
P(F=F1|S==S3) = 0
P(F=F2|S==S1) = 1/4
P(F=F2|S==S2) = 1/3
P(F=F2|S==S3) = 1/3
P(F=F3|S==S1) = 0
P(F=F3|S==S2) = 1/3
P(F=F3|S==S3) = 1/3
P(F=F4|S==S1) = 1/4
P(F=F4|S==S2) = 0
P(F=F4|S==S3) = 1/3
P(F=F5|S==S1) = 1/4
P(F=F5|S==S2) = 0
P(F=F5|S==S3) = 0


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [6]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    words1 = S1.split()    #split the string into diff words and stored the words into list format
    words2 = S2.split()
    a = 0                 #counts the how many same words are present in two lists
    for i in range(len(words1)):
        for j in range(len(words2)):
            if words1[i] == words2[j]:
                a = a + 1
    b = [word for word in words1 if word not in words2]  #prints the words which present in list1 but not present in list2
    c = [word for word in words2 if word not in words1]  #prints the words which present in list2 but not present in list1
    return a, b, c       #retun the values



S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print('\n',"a.",a,'\n',"b.",b,'\n',"c.",c)    #prints the values


 a. 7 
 b. ['first', 'F', '5'] 
 c. ['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [11]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
import math
def compute_log_loss(A):    #creating a function
    for i in range(len(A)):  #range will be length of a list = 8
        sum = 0
        n = len(A)
        for i in range(len(A)):
            sum += ((A[i][0] * math.log10(A[i][1])) + ((1 - A[i][0]) * math.log10(1 - A[i][1])))   #eqn given in the question 
            sum1 = (-1/n) * sum
    print(sum1)     #prints the values
       

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
compute_log_loss(A)               #calling the functions


0.42430993457031635


...

...

...

....